version: "3.8"
services:
  eureka-service:
    build:
      context: eureka-service
      dockerfile: Dockerfile
    image: eureka_service
    container_name: eureka_service
    hostname: eureka-service
    ports:
      - "80:8761"
  gateway_service:
    build:
      context: gateway-service
      dockerfile: Dockerfile
    image: gateway_service
    container_name: gateway_service
    ports:
      - "8080:8080"
    depends_on:
      - eureka-service
      - product_service
      - inventory_service
  product_service:
    build: 
      context: product-service
      dockerfile: Dockerfile
    image: product_service
    container_name: product_service
    ports:
      - "9090:9090"
    environment:
      - MONGODB_URI=mongodb://product_service_db
    depends_on:
      - product_service_db
      - redis
      - eureka-service
  inventory_service:
    build:
      context: inventory-service
      dockerfile: Dockerfile
    image: inventory_service
    restart: unless-stopped
    container_name: inventory_service
    #    environment:
    #  - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka_service:8761/eureka
    ports:
      - "9091:9091"
    depends_on:
      - inventory_service_db
      - eureka-service
  product_service_db:
    restart: always
    image: mongo:latest
    container_name: product_service_db
    ports:
      - "27017:27017"
  inventory_service_db:
    image: mysql:8
    restart: unless-stopped
    container_name: inventory_service_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=inventory
      - MYSQL_USER=inventory
      - MYSQL_DATABASE=inventory_service
    ports:
      - "3306:3306"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
