version: "3"
services:
  product_service:
    build: 
      context: product-service
      dockerfile: Dockerfile
    image: product_service
    container_name: product_service
    ports:
      - "9090:9090"
    environment:
      - MONGODB_URI=mongodb://product_service_db
    depends_on:
      - product_service_db
      - redis
  inventory_service:
    build:
      context: inventory-service
      dockerfile: Dockerfile
    image: inventory_service
    restart: unless-stopped
    container_name: inventory_service
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://inventory_service_db:3306/inventory_service?createDatabaseIfNotExist=true
#      - SPRING_DATASOURCE_USERNAME=inventory
#      - SPRING_DATASOURCE_PASSWORD=inventory
    ports:
      - "9091:9091"
    depends_on:
      - inventory_service_db
  product_service_db:
    restart: always
    image: mongo:latest
    container_name: product_service_db
    ports:
      - "27017:27017"
  inventory_service_db:
    image: mysql:8
    restart: unless-stopped
    container_name: inventory_service_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=inventory
      - MYSQL_USER=inventory
      - MYSQL_DATABASE=inventory_service
    ports:
      - "3306:3306"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
