spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
    config:
      uri: http://localhost:8888
  profiles:
    active: dev
  config:
    import: 'configserver:'
server:
  port: 8080