spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory
  profiles:
    active: test
server:
  port: 8080