spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888
  kafka:
    bootstrap-servers: kafka:29092
  datasource:
    username: sa
    password: sa
    url: jdbc:h2:file:./data/demo;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka
server:
  port: 9093