spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/product_service
      # run local a mongo container
      # docker run -p 27017:27017 mongo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: localhost
    port: 6379
    # run local a redis container
    # docker run -p 6379:6379 redis

eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka