spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/product_service
      # run local a mongo container
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka