spring:
  data:
    mongodb:
      uri: mongodb://product_service_db:27017/product_service
  redis:
    host: redis
    port: 6379
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka