spring:
  application:
    name: eureka-service
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://eureka-service:${server.port}/eureka/
  instance:
    hostname: eureka-service.com
