spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: git@github.com:rashed-08/config-service.git
          clone-on-start: true
          search-paths:
            - '*service'
          default-label: master
server:
  port: 8888
