spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: git@github.com:rashed-08/config-service.git
          clone-on-start: true
          search-paths:
            - '{profile}'
          default-label: master
          strict-host-key-checking: false
server:
  port: 8888
