name: Ponno Bazar CI with Maven

on:
  push:
    branches: [ inventory_service, product_service ]
  pull_request:
    branches: [ master, development, staging ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build Product Service
      run: cd product-service && mvn clean install
    - name: Build Inventory Service
      run: cd inventory-service && mvn clean install
    - name: Build Order Service
      run: cd order-service && mvn clean install   
    - name: Build Gateway Service
      run: cd gateway-service && mvn clean install
    - name: Build Eureka Service
      run: cd eureka-service && mvn clean install
    - name: Build & push Docker image
      run: docker-compose up -d
