name: Product_Service

on:
  push:
    branches: [ inventory_service, product_service ]
  pull_request:
    branches: [ master, development, staging ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose up -d
